<?php $cli = new League\CLImate\CLImate();
/** @var Modules\ViewModel\Console\ListViewModel $viewModel */
$viewModel = $this->viewModel()->getCurrent();

$cli->bold('Used packages:');
$cli->backgroundLightCyan(
    '  <black>'
    . sprintf("%-16s", 'Version')
    . sprintf("%-40s", 'Namespace')
    . sprintf("%-40s", 'Name')
    . "</black>"
);

$packages = [];

foreach($viewModel->getPackages() as $package) {
    $cli->out(
        '  '
        . sprintf("%-16s", $package->getVersion())
        . sprintf("%-40s", $package->getNamespace())
        . "<green>"
        . sprintf("%-40s", $package->getName())
        . "</green>"
    );

    $packages[$package->getNamespace()] = array(
        'name'    => $package->getName(),
        'version' => $package->getVersion(),
    );
}

$cli->br();
$cli->bold('Used modules:');
$cli->backgroundLightCyan(
    '  <black>'
    . sprintf("%-16s", 'Version')
    . sprintf("%-40s", 'Namespace')
    . sprintf("%-40s", 'Name')
    . "</black>"
);

foreach ($viewModel->getLoadedModules() as $moduleName => $module) {

    if (isset($packages[$moduleName])) {
        $cli->out(
            '  '
            . sprintf("%-16s", $packages[$moduleName]['version'])
            . sprintf("%-40s", $moduleName)
            . "<green>"
            . sprintf("%-40s", $packages[$moduleName]['name'])
            . "</green>"
        );
    } else {
        $cli->out(
            '  '
            . sprintf("%-16s", '')
            . sprintf("%-40s", $moduleName)
            . "<green>"
            . sprintf("%-40s", $moduleName)
            . "</green>"
        );
    }

}
