<?php $cli = new League\CLImate\CLImate();
/** @var Modules\ViewModel\Console\ListViewModel $viewModel */
$viewModel = $this->viewModel()->getCurrent();

$cli->bold('Used packages:');
$cli->backgroundLightCyan(
    '  <black>'
    . sprintf("%-16s", 'Version')
    . sprintf("%-20s", 'Namespace')
    . sprintf("%-40s", 'Name')
    . "</black>"
);

$packages = [];

foreach($viewModel->getPackages() as $package) {
    $cli->out(
        '  '
        . sprintf("%-16s", $package->getVersion())
        . sprintf("%-20s", $package->getNamespace())
        . "<green>"
        . sprintf("%-40s", $package->getName())
        . "</green>"
    );

    $packages[$package->getNamespace()] = array(
        'name'    => $package->getName(),
        'version' => $package->getVersion(),
    );
}

$cli->br();
$cli->bold('Used modules:');
$cli->backgroundLightCyan(
    '  <black>'
    . sprintf("%-16s", 'Version')
    . sprintf("%-14s", 'Status')
    . sprintf("%-20s", 'Namespace')
    . sprintf("%-40s", 'Name')
    . "</black>"
);

foreach ($viewModel->getModules() as $module) {

    if (in_array($module->getStatusName(), ['need install', 'need upgrade'])) {

        $cli->out(
            '  '
            . sprintf("%-16s", $module->getVersion())
            . "<yellow>"
            . sprintf("%-14s", $module->getStatusName())
            . "</yellow>"
            . sprintf("%-20s", $module->getNamespace())
            . "<green>"
            . sprintf("%-40s", $module->getName())
            . "</green>"
        );

    } else {
        $cli->out(
            '  '
            . sprintf("%-16s", $module->getVersion())
            . sprintf("%-14s", $module->getStatusName())
            . sprintf("%-20s", $module->getNamespace())
            . "<green>"
            . sprintf("%-40s", $module->getName())
            . "</green>"
        );
    }

}

$cli->br();
$cli->out('Statuses may be one of [<yellow>active</yellow>, <yellow>need install</yellow>, <yellow>need upgrade</yellow>, <yellow>absent</yellow>]');
$cli->br();
$cli->bold('Actions');
$cli->out(
    '  '
    . "<green>"
    . sprintf("%-40s", 'index.php modules install MODULENAME')
    . "</green>"
    . sprintf("%-40s", 'Install module in system and run initial migrations')
);
$cli->out(
    '  '
    . "<green>"
    . sprintf("%-40s", 'index.php modules upgrade MODULENAME')
    . "</green>"
    . sprintf("%-40s", 'Upgrade module and run module migrations')
);
$cli->out(
    '  '
    . "<green>"
    . sprintf("%-40s", 'index.php modules remove MODULENAME')
    . "</green>"
    . sprintf("%-40s", 'Remove module and run remove migrations')
);